Implement breakpointObserver.
carbon-design-system/carbon-components-svelte pull request #1092
Opened 2022-02-12 15:34 UTC by brunnerh

For #1069

Drop breakpoints constant export from Breakpoint component.
Expose breakpoints constant separately and freeze it.
Change `match` event to `change`, because it is now based on store and captures initial value change.

Naming and file organization is up for debate of course as this has no precedent in this repository...

2022-02-15 16:10 UTC, brunnerh commented
@metonym If you have suggestions on how to proceed from here, that would be appreciated. Everything except documentation seems to be tied to automated processes which are not set up to handle this.

2022-02-17 01:43 UTC, metonym requested changes
This is looking good.

I see what you mean about the preprocessor breaking and inability to generate TypeScript definitions for the observer/constants.

1. As a workaround, let's remove the newly added exports from `index.js` so that direct importing works.
2. I'd prefer the `BreakpointSize` and `BreakpointValue` interfaces be preserved in the Svelte file/TypeScript definitions. This is useful because it shows the possible values for `BreakpointSize` in the component index and docs.
3. Manual TypeScript definitions for `constants.js` and `breakpointObserver.js` should work for now.

2022-02-20 15:53 UTC, brunnerh commented
Ideally the types could be sourced from a single definition. Maybe additional syntax could be introduced so the types can be re-exported from a `.d.ts` file or another module without duplication.

Removing the index export is not great. I tried to mitigate this by adding a separate build output, so the observer could be imported from the `lib` directory (to keep the separation of potentially internal code and public package API), but ran into trouble with the Svelte output (`'Function called outside component initialization'`).

2022-02-20 23:01 UTC, metonym requested changes
Nits:

1. rename "constants.js" to "breakpoints.js"

I was expecting that "breakpoints" would be in a file of the same name so that I could get TS definitions when importing directing:

```
import { breakpoints } from "carbon-components-svelte/src/Breakpoint/breakpoints";
```

It's also more descriptive than "constants."

2. I'd prefer to avoid reference types where possible

It's easier to find `BreakpointSize` and `BreakpointValue` types if they are in `breakpoints.d.ts`

`breakpoints.d.ts` should house the types:

```ts
export type BreakpointSize = "sm" | "md" | "lg" | "xlg" | "max";
// ...
```

And then breakpointObserver.js can access it using import types:

```js
/** @type {Record<import("./breakpoints").BreakpointSize, MediaQueryList>} */
```

Finally, in `breakpointObserver.d.ts`, I'd prefer the types be imported at the top:

```ts
import type { Readable, Subscriber, Unsubscriber } from "svelte/store";
import type { BreakpointSize, BreakpointValue } from "./breakpoints";
```

2022-02-20 23:04 UTC, metonym commented on src/Breakpoint/index.d.ts
> +export { breakpoints } from "./constants";
Missing the `Breakpoint` Svelte component.

```suggestion
export { default as Breakpoint } from "./Breakpoint.svelte";
export { breakpointObserver } from "./breakpointObserver";
export { breakpoints } from "./constants";

```

2022-02-27 12:53 UTC, brunnerh commented
> I was expecting that "breakpoints" would be in a file of the same name so that I could get TS definitions when importing...

To my knowledge, the naming should not matter, as long as the files have their respective typings; I renamed it though.

Regarding the inline use of `import("./breakpoints").BreakpointSize` instead of `<reference ...`, personally I am not a fan because of its verbosity and duplication, but then again, I would write everything directly in TypeScript, where that could just be a regular import statement.

The component export missing along with having all those inline Svelte imports was a side effect of using `tsc` to generate the declaration files without giving it enough context. Now that the `BreakpointSize`/`BreakpointValue` types are part of one of these files that is probably no longer an option if anything changes. It would be nice if all that would just be part of the build process, though.

2022-03-02 15:39 UTC, metonym approved these changes
Nice work – thanks for also updating the docs.

2022-03-08 16:38 UTC, merged