feat: svelte indexing
carbon-design-system/carbon-components-svelte pull request #1266
Opened 2022-04-27 13:51 UTC by andreancardona

This issue closes:

https://github.com/carbon-design-system/carbon-platform/issues/516

## Description:

- This PR indexes `carbon-components-svelte`

## Note:

We still need the following thumbnails:
- breakpoint
      - button-set
      - clickable-tile
      - composed-modal
      - context-menu
      - expandable-tile
      - fluid form
      - image-loader
      - inline-notification
      - local-storage
      - ordered-list
      - password-input
      - recursive-list
      - selectable-tile
      - skeleton-placeholder
      - skeleton-text
      - toast-notification
      - tooltip-icon
      - truncate
      - unordered-list

2022-04-27 16:10 UTC, francinelucca requested changes

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +  externalDocsUrl: https://react.carbondesignsystem.com
```suggestion
  externalDocsUrl: https://carbon-components-svelte.onrender.com
```

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    description: ''
```suggestion
```

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +        url: https://carbon-components-svelte.onrender.com/components/DatePicker
wrong url

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    description: ''
```suggestion
```

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    noIndex: true
should this be noIndex?

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    description: ''
```suggestion
```

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +    description: ''
```suggestion
```

2022-04-27 16:10 UTC, francinelucca commented on carbon.yml
> +      - data-display
```suggestion
      - data-display
      
```

2022-04-28 15:02 UTC, francinelucca commented on carbon.yml
> +        url: https://carbon-components-svelte.onrender.com/components/ProgressIndicator
wrong url

2022-04-28 15:21 UTC, francinelucca commented on carbon.yml
> +    externalDocsUrl: https://www.carbondesignsystem.com/components/text-area/usage
this takes me to a 404 page

2022-04-28 15:41 UTC, andreancardona commented on carbon.yml
> +    externalDocsUrl: https://www.carbondesignsystem.com/components/text-area/usage
```suggestion
```

2022-04-29 20:47 UTC, francinelucca reviewed
LGTM 🎉 , minor comment

2022-04-29 20:47 UTC, francinelucca commented on carbon.yml
> +    name: local-storage
is this name ok?

2022-05-03 15:01 UTC, francinelucca reviewed
LGTM

2022-05-03 16:50 UTC, aubrey-oneal commented on carbon.yml
> +      - structural-navigation
Delete structural-navigation. Add shell.

2022-05-03 16:50 UTC, aubrey-oneal commented on carbon.yml
> +      - input-control
Approved 👍

2022-05-03 16:51 UTC, aubrey-oneal commented on carbon.yml
> +      - input-control
Delete input-control. Add contextual-navigation.

2022-05-03 16:52 UTC, aubrey-oneal commented on carbon.yml
> +      - contextual-navigation
Keep input-control. Delete contextual-navigation.

2022-05-03 16:55 UTC, aubrey-oneal commented on carbon.yml
> +      - input-control
Delete input control. Add data-display and content element (has the same tags as Accordion).

2022-05-03 16:57 UTC, aubrey-oneal commented on carbon.yml
> +      - shell
Keep shell. Add media tag.

2022-05-03 16:59 UTC, aubrey-oneal commented on carbon.yml
> +      - input-control
Approved 👍

2022-05-03 17:02 UTC, aubrey-oneal commented on carbon.yml
> +      - data-display
Delete data-display and contextual navigation. Add form.

2022-05-03 17:05 UTC, aubrey-oneal commented on carbon.yml
> +      - shell
Delete shell. Add system-feedback.

2022-05-03 17:07 UTC, aubrey-oneal commented on carbon.yml
> +      - contextual-navigation
Delete contextual-navigation. Add data-display.

2022-05-03 17:08 UTC, aubrey-oneal requested changes
Added changes to tags.

2022-05-03 17:45 UTC, andreancardona commented on carbon.yml
> +      - structural-navigation
```suggestion
      - shell
```

2022-05-03 17:46 UTC, andreancardona commented on carbon.yml
> +      - input-control
```suggestion
      - contextual-navigation
```

2022-05-03 17:46 UTC, andreancardona commented on carbon.yml
> +      - contextual-navigation
```suggestion
```

2022-05-03 17:47 UTC, andreancardona commented on carbon.yml
> +      - input-control
```suggestion
      - data-display
      - content-element
```

2022-05-03 17:47 UTC, andreancardona commented on carbon.yml
> +      - shell
```suggestion
      - shell
      - media
```

2022-05-03 17:48 UTC, andreancardona commented on carbon.yml
> +      - data-display
```suggestion
      - contextual-navigation
      - form
```

2022-05-03 17:48 UTC, andreancardona commented on carbon.yml
> +      - input-control
```suggestion
      - data-display
```

2022-05-03 17:49 UTC, andreancardona commented on carbon.yml
> +      - shell
```suggestion
      - system-feedback
```

2022-05-03 17:49 UTC, andreancardona commented on carbon.yml
> +      - contextual-navigation
```suggestion
      - data-display
```

2022-05-03 17:59 UTC, andreancardona commented on carbon.yml
> +      - contextual-navigation
```suggestion
```

2022-05-04 18:04 UTC, andreancardona commented
@metonym Hey Eric! Hope all is well - do you mind merging this PR when you get a chance :).

2022-05-04 18:11 UTC, metonym approved these changes
@andreancardona LGTM

Kudos to the designer – lovely work on the thumbnails.

2022-05-04 18:12 UTC, merged