fix(tree-view-node-list): remove unused `expanded` prop
carbon-design-system/carbon-components-svelte pull request #1631
Opened 2023-01-16 22:37 UTC by metonym

Fixes #1630

**Changes**

- remove unused `expanded` prop from `TreeViewNodeList`
- fix `TreeViewIcons` example by removing `expanded: true`

**Notes**

`TreeViewNodeList` and `TreeViewNode` are not exported from the entry point (`src/index.js`) because they are considered "internal" component. As such, running `yarn build:docs` has no effect as it only generates types for components exported from the root.

2023-01-17 04:58 UTC, theetrain requested changes
Component changes look good, but some documentation changes are needed:

1. Remove `expanded` property in default example paragraph

   ![image](https://user-images.githubusercontent.com/12798751/212813298-7e3263f5-e207-4800-9591-2db1cb0fc2b4.png)

2. Update the `TreeNode` interface, removing the `expanded?` optional key:

   https://github.com/carbon-design-system/carbon-components-svelte/blob/7701c012a571a7cf7f6180ca144dcc75b36b2154/src/TreeView/TreeView.svelte#L4

2023-01-17 16:17 UTC, metonym commented
Added the suggested changes; best reviewed by commit.

2023-01-17 17:50 UTC, theetrain approved these changes
This looks good. I consider this a breaking change due to the type changes being reflected on the docs. I don't consider removing the `expanded` prop from `TreeViewNodeList.svelte` as a breaking change since it's internal-facing; users won't directly engage with that component.

2023-01-18 01:55 UTC, merged

2023-01-18 02:11 UTC, theetrain commented
This has been released in [v0.72.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.72.0).