[HeaderNavItem ] Allow custom HTML with `slot`
carbon-design-system/carbon-components-svelte pull request #1693
Opened 2023-03-17 13:50 UTC by pierre-H

2023-03-17 14:36 UTC, brunnerh commented
Probably missing a docs re-build, which should add the slot there.

2023-03-18 17:32 UTC, metonym requested changes
Could you run `yarn build:docs` and commit the updated docs/types?

2023-03-25 20:37 UTC, metonym approved these changes

2023-04-13 21:50 UTC, metonym approved these changes

2023-05-02 23:23 UTC, merged

2023-05-19 01:37 UTC, theetrain commented
Now available in [v0.74.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.74.0)