remove nbsp that can cause glitch on load
carbon-design-system/carbon-components-svelte pull request #1764
Opened 2023-07-11 09:51 UTC by p0lish

I've noticed that the ui shell has a little glitch during load in our app.

![image](https://github.com/carbon-design-system/carbon-components-svelte/assets/2803621/f69b3972-957b-4095-a963-d218eaf66e69)

The `Â` disappearing after load but it causes a glitch.

The root cause is an `&nbsp;` character in the company text span.
Maybe somebody else faced with this glitch too, so I created a small improvement for that.

2023-07-11 10:49 UTC, brunnerh commented
That just looks like an encoding issue, did you set a/the correct `charset` in the `content-type` header or a `meta` tag?

2023-07-11 18:28 UTC, metonym requested changes
WDYT about making the `company` prop slottable so the end user can override this behavior?

```svelte
{#if company || $$slots.company}
  <span class:bx--header__name--prefix="{true}"><slot name="company">{company}&nbsp;</slot></span>
{/if}
```

2023-07-12 09:41 UTC, p0lish commented
> WDYT about making the `company` prop slottable so the end user can override this behavior?
> 
> ```svelte
> {#if company || $$slots.company}
>   <span class:bx--header__name--prefix="{true}"><slot name="company">{company}&nbsp;</slot></span>
> {/if}
> ```

Hey, I think its a good idea. Thanks.

2023-07-12 11:11 UTC, brunnerh commented on types/UIShell/Header.svelte.d.ts
> +   * Alternatively, use the named slot "company" (e.g., <span slot="company">...</span>)
Might want to enclose the HTML example in `` ` ``, as JS doc is commonly interpreted as Markdown.
Would also terminate line above with a `.`, potentially followed by two spaces, which indicates a manual line break.

You e.g. currently get this in VS Code:
![image](https://github.com/carbon-design-system/carbon-components-svelte/assets/834235/30ce6ad9-a22b-4042-9a56-65ce1f9b6c51)

2023-07-12 15:21 UTC, metonym commented on src/UIShell/Header.svelte
> +<style>
The style override can be removed

2023-07-13 14:27 UTC, brunnerh approved these changes

2023-07-13 14:33 UTC, merged

2023-07-13 15:25 UTC, brunnerh commented
Ahhh, the doc fixes should of course have been made directly in `Header.svelte`, they got reverted by the docs re-build.

2023-07-13 15:28 UTC, metonym commented
@brunnerh Nice catch – I can add that back in.

2023-07-13 18:01 UTC, metonym commented
Released in [v0.77.0](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.77.0)