chore(ibm-common): add mandatory IBM instrumentation tags
carbon-design-system/carbon-components-svelte pull request #1983
Opened 2024-07-16 19:20 UTC by jeffchew

Adding mandatory IBM intrumentation tags for Carbon Svelte.

2024-07-17 14:28 UTC, jeffchew commented
@metonym fyi, this tag and footer needs to be added due to a recent IBM OPRT audit. This needs to be live by mid-August.

2024-07-17 15:46 UTC, metonym commented on docs/src/global.css
> +  height: calc(100% - 120px);
The magic number may need some adjusting, as the side nav appears to be cut off.

<img width="994" alt="Screenshot 2024-07-17 at 8 45 21 AM" src="https://github.com/user-attachments/assets/03edc5e5-a2f2-496e-a017-780569638a34">

2024-07-17 15:46 UTC, metonym commented on docs/src/global.css
> +  height: calc(100% - 120px);
<img width="1314" alt="Screenshot 2024-07-17 at 8 46 26 AM" src="https://github.com/user-attachments/assets/641999bd-4f65-421f-846e-965cdafca324">

2024-07-17 15:47 UTC, metonym requested changes
Appreciate the heads up – reviewed.

2024-07-17 16:42 UTC, metonym reviewed
@jeffchew I'm viewing this locally on Chrome – weirdly, the Sidenav height doesn't seem to fill in the viewport height until the footer is in view.

https://github.com/user-attachments/assets/13ef7d43-2281-4d2f-8ef5-922834d13191

2024-07-17 16:47 UTC, jeffchew commented
The sidenav is fixed position and I think it probably won't be able to fill the viewport height without a layout rewrite which is what I was trying to avoid.

2024-07-18 16:01 UTC, metonym commented
Gotcha – I'll take a closer look at this.

2024-08-06 14:38 UTC, jeffchew commented
@metonym wondering if we can merge this for now? We need to complete the compliance remediation by the 15th.

2024-08-07 15:45 UTC, metonym commented
Moved to #1988 

I built upon this PR so that the footer does not obstruct the side nav.

<img width="1510" alt="Screenshot 2024-08-07 at 8 07 42 AM" src="https://github.com/user-attachments/assets/bbe605f9-76ff-432c-b8a8-685df9a8eb22">

2024-08-07 15:58 UTC, closed without merging

2024-08-07 16:06 UTC, jeffchew commented
> Moved to #1988
> 
> I built upon this PR so that the footer does not obstruct the side nav.
> 

Thank you so much @metonym !